name: Deploy Vue Docker to Azure

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image (optional, for ACR)
      run: |
        docker build -t portal-app:latest .
        docker tag portal-app:latest barepfd-b3agdua3cvevhnhr.azurecr.io/portal-app:latest
        docker push barepfd-b3agdua3cvevhnhr.azurecr.io/portal-app:latest

    - name: Deploy to Azure Web App (Container)
      uses: azure/webapps-deploy@v2
      with:
        app-name: barep-prd
        images: barepfd-b3agdua3cvevhnhr.azurecr.io/portal-app:latest
